-- 001_create_cargos_e_atribuicoes.sql

-- =========================
-- Tabela: cargos
-- =========================
CREATE TABLE IF NOT EXISTS public.cargos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT NOT NULL UNIQUE,              -- ex: MESTRE_BANQUETES, TESOUREIRO
  nome_exibicao TEXT NOT NULL,              -- ex: Mestre de Banquetes
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================
-- Tabela: atribuicoes_cargo
-- =========================
CREATE TABLE IF NOT EXISTS public.atribuicoes_cargo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cargo_id BIGINT NOT NULL REFERENCES public.cargos(id),
  obreiro_id UUID NOT NULL REFERENCES public.obreiros(id),
  inicio_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  fim_em TIMESTAMPTZ NULL,
  observacao TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_periodo_atribuicao
    CHECK (fim_em IS NULL OR fim_em >= inicio_em)
);

-- Regra: só pode existir 1 atribuição ativa por cargo (fim_em IS NULL)
CREATE UNIQUE INDEX IF NOT EXISTS ux_atribuicoes_cargo_ativo_por_cargo
  ON public.atribuicoes_cargo(cargo_id)
  WHERE fim_em IS NULL;

-- Performance: buscar cargos ativos de um obreiro
CREATE INDEX IF NOT EXISTS ix_atribuicoes_cargo_ativo_por_obreiro
  ON public.atribuicoes_cargo(obreiro_id)
  WHERE fim_em IS NULL;
