-- 005_central_operacional_sessoes.sql
-- Fundacao do nucleo de sessoes, confirmacoes, agape, publicacoes e historico.

-- Garante que o cargo SECRETARIO exista tambem no banco ja provisionado.
INSERT INTO public.cargos (codigo, nome_exibicao, ativo)
VALUES ('SECRETARIO', 'Secretario', TRUE)
ON CONFLICT (codigo) DO UPDATE
SET
  nome_exibicao = EXCLUDED.nome_exibicao,
  ativo = EXCLUDED.ativo;

-- =========================================================
-- Tabela principal: sessoes
-- =========================================================

ALTER TABLE public.sessoes
  ADD COLUMN IF NOT EXISTS data_hora_inicio TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS data_hora_fim TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS tipo_sessao TEXT NULL,
  ADD COLUMN IF NOT EXISTS grau_sessao TEXT NULL,
  ADD COLUMN IF NOT EXISTS titulo TEXT NULL,
  ADD COLUMN IF NOT EXISTS resumo_publico TEXT NULL,
  ADD COLUMN IF NOT EXISTS observacao_interna TEXT NULL,
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'planejada',
  ADD COLUMN IF NOT EXISTS agape_ativo BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS publicada_em TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS cancelada_em TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS realizada_em TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS criada_por UUID NULL REFERENCES public.obreiros(id),
  ADD COLUMN IF NOT EXISTS atualizada_por UUID NULL REFERENCES public.obreiros(id),
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

UPDATE public.sessoes
   SET data_hora_inicio = COALESCE(data_hora_inicio, data::timestamptz),
       tipo_sessao = COALESCE(tipo_sessao, tipo),
       grau_sessao = COALESCE(grau_sessao, grau),
       resumo_publico = COALESCE(resumo_publico, pauta)
 WHERE data_hora_inicio IS NULL
    OR tipo_sessao IS NULL
    OR grau_sessao IS NULL
    OR resumo_publico IS NULL;

ALTER TABLE public.sessoes
  ALTER COLUMN data_hora_inicio SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
      FROM pg_constraint
     WHERE conname = 'chk_sessoes_status'
       AND conrelid = 'public.sessoes'::regclass
  ) THEN
    ALTER TABLE public.sessoes
      ADD CONSTRAINT chk_sessoes_status
      CHECK (status IN ('planejada', 'publicada', 'alterada', 'cancelada', 'realizada'));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
      FROM pg_constraint
     WHERE conname = 'chk_sessoes_periodo'
       AND conrelid = 'public.sessoes'::regclass
  ) THEN
    ALTER TABLE public.sessoes
      ADD CONSTRAINT chk_sessoes_periodo
      CHECK (data_hora_fim IS NULL OR data_hora_fim >= data_hora_inicio);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS ix_sessoes_data_hora_inicio
  ON public.sessoes(data_hora_inicio);

CREATE INDEX IF NOT EXISTS ix_sessoes_status_data
  ON public.sessoes(status, data_hora_inicio);

-- =========================================================
-- Confirmacoes da sessao
-- =========================================================

CREATE TABLE IF NOT EXISTS public.confirmacoes_sessao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sessao_id INTEGER NOT NULL REFERENCES public.sessoes(id) ON DELETE CASCADE,
  obreiro_id UUID NOT NULL REFERENCES public.obreiros(id) ON DELETE CASCADE,
  status_confirmacao TEXT NOT NULL DEFAULT 'confirmado',
  participara_agape BOOLEAN NOT NULL DEFAULT FALSE,
  observacao TEXT NULL,
  respondido_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_confirmacoes_sessao_obreiro UNIQUE (sessao_id, obreiro_id),
  CONSTRAINT chk_confirmacoes_sessao_status
    CHECK (status_confirmacao IN ('confirmado', 'ausente'))
);

CREATE INDEX IF NOT EXISTS ix_confirmacoes_sessao_sessao_status
  ON public.confirmacoes_sessao(sessao_id, status_confirmacao);

CREATE INDEX IF NOT EXISTS ix_confirmacoes_sessao_agape
  ON public.confirmacoes_sessao(sessao_id, participara_agape);

CREATE INDEX IF NOT EXISTS ix_confirmacoes_sessao_obreiro
  ON public.confirmacoes_sessao(obreiro_id);

-- =========================================================
-- Presenca efetiva da sessao
-- =========================================================

CREATE TABLE IF NOT EXISTS public.presencas_sessao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sessao_id INTEGER NOT NULL REFERENCES public.sessoes(id) ON DELETE CASCADE,
  obreiro_id UUID NOT NULL REFERENCES public.obreiros(id) ON DELETE CASCADE,
  presente BOOLEAN NOT NULL DEFAULT TRUE,
  observacao TEXT NULL,
  registrado_por UUID NULL REFERENCES public.obreiros(id),
  registrado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_presencas_sessao_obreiro UNIQUE (sessao_id, obreiro_id)
);

CREATE INDEX IF NOT EXISTS ix_presencas_sessao_sessao
  ON public.presencas_sessao(sessao_id, presente);

CREATE INDEX IF NOT EXISTS ix_presencas_sessao_obreiro
  ON public.presencas_sessao(obreiro_id);

-- =========================================================
-- Publicacoes da sessao
-- =========================================================

CREATE TABLE IF NOT EXISTS public.publicacoes_sessao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sessao_id INTEGER NOT NULL REFERENCES public.sessoes(id) ON DELETE CASCADE,
  tipo_publicacao TEXT NOT NULL,
  canal TEXT NOT NULL DEFAULT 'erp',
  conteudo TEXT NULL,
  publicado_por UUID NULL REFERENCES public.obreiros(id),
  publicado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_publicacoes_sessao_tipo
    CHECK (tipo_publicacao IN ('agenda_oficial', 'resumo_proxima_sessao', 'alteracao_relevante')),
  CONSTRAINT chk_publicacoes_sessao_canal
    CHECK (canal IN ('erp', 'telegram', 'interno'))
);

CREATE INDEX IF NOT EXISTS ix_publicacoes_sessao_sessao
  ON public.publicacoes_sessao(sessao_id, publicado_em DESC);

-- =========================================================
-- Historico operacional da sessao
-- =========================================================

CREATE TABLE IF NOT EXISTS public.historico_sessao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sessao_id INTEGER NOT NULL REFERENCES public.sessoes(id) ON DELETE CASCADE,
  acao TEXT NOT NULL,
  valor_anterior JSONB NULL,
  valor_novo JSONB NULL,
  autor_id UUID NULL REFERENCES public.obreiros(id),
  observacao TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_historico_sessao_sessao
  ON public.historico_sessao(sessao_id, created_at DESC);
