-- 006_secretaria_fundacao.sql
-- Fundacao do modulo operacional da Secretaria.

ALTER TABLE public.obreiros
  ADD COLUMN IF NOT EXISTS data_elevacao DATE NULL,
  ADD COLUMN IF NOT EXISTS data_exaltacao DATE NULL,
  ADD COLUMN IF NOT EXISTS telegram_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS potencia_login TEXT NULL,
  ADD COLUMN IF NOT EXISTS acesso_potencia_liberado BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS acesso_potencia_liberado_em TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS observacao_secretaria TEXT NULL;

CREATE INDEX IF NOT EXISTS ix_obreiros_telegram_id
  ON public.obreiros(telegram_id);

CREATE TABLE IF NOT EXISTS public.trabalhos_sessao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sessao_id INTEGER NOT NULL REFERENCES public.sessoes(id) ON DELETE CASCADE,
  tipo_trabalho TEXT NOT NULL DEFAULT 'peca_arquitetura',
  titulo TEXT NOT NULL,
  autor_id UUID NULL REFERENCES public.obreiros(id),
  autor_nome_livre TEXT NULL,
  arquivo_pdf_path TEXT NULL,
  status_envio_potencia TEXT NOT NULL DEFAULT 'pendente',
  enviado_potencia_em TIMESTAMPTZ NULL,
  criado_por UUID NULL REFERENCES public.obreiros(id),
  observacao TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_trabalhos_sessao_tipo
    CHECK (tipo_trabalho IN ('peca_arquitetura', 'trabalho', 'prancha', 'outro')),
  CONSTRAINT chk_trabalhos_sessao_envio
    CHECK (status_envio_potencia IN ('pendente', 'enviado', 'dispensado'))
);

CREATE INDEX IF NOT EXISTS ix_trabalhos_sessao_sessao
  ON public.trabalhos_sessao(sessao_id, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_trabalhos_sessao_autor
  ON public.trabalhos_sessao(autor_id);

CREATE TABLE IF NOT EXISTS public.publicacoes_secretaria (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sessao_id INTEGER NULL REFERENCES public.sessoes(id) ON DELETE SET NULL,
  tipo_publicacao TEXT NOT NULL,
  titulo TEXT NOT NULL,
  origem TEXT NULL,
  conteudo TEXT NULL,
  canal_destino TEXT NOT NULL DEFAULT 'grupo',
  status_publicacao TEXT NOT NULL DEFAULT 'rascunho',
  publicado_por UUID NULL REFERENCES public.obreiros(id),
  publicado_em TIMESTAMPTZ NULL,
  observacao TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_publicacoes_secretaria_tipo
    CHECK (tipo_publicacao IN ('agenda_oficial', 'proxima_sessao', 'informativo_potencia', 'convite_externo', 'comunicado')),
  CONSTRAINT chk_publicacoes_secretaria_canal
    CHECK (canal_destino IN ('web', 'grupo', 'interno', 'misto')),
  CONSTRAINT chk_publicacoes_secretaria_status
    CHECK (status_publicacao IN ('rascunho', 'publicado', 'cancelado'))
);

CREATE INDEX IF NOT EXISTS ix_publicacoes_secretaria_status
  ON public.publicacoes_secretaria(status_publicacao, created_at DESC);
