-- 007_balaustres_votacao.sql
-- Estrutura formal para balaustre e fluxo de votacao.

CREATE TABLE IF NOT EXISTS public.balaustres (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sessao_id INTEGER NOT NULL REFERENCES public.sessoes(id) ON DELETE CASCADE,
  numero_balaustre TEXT NULL,
  template_versao TEXT NOT NULL DEFAULT 'oficial-v1',
  texto_final TEXT NULL,
  dados_capturados JSONB NULL,
  preparado_por UUID NULL REFERENCES public.obreiros(id),
  preparado_em TIMESTAMPTZ NULL,
  apto_votacao BOOLEAN NOT NULL DEFAULT FALSE,
  apto_votacao_em TIMESTAMPTZ NULL,
  apto_votacao_por UUID NULL REFERENCES public.obreiros(id),
  status TEXT NOT NULL DEFAULT 'rascunho',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_balaustres_sessao UNIQUE (sessao_id),
  CONSTRAINT chk_balaustres_status
    CHECK (status IN ('rascunho', 'apto_votacao', 'em_votacao', 'aprovado', 'em_correcao', 'rejeitado'))
);

CREATE INDEX IF NOT EXISTS ix_balaustres_status
  ON public.balaustres(status, updated_at DESC);

CREATE TABLE IF NOT EXISTS public.balaustre_votacoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  balaustre_id BIGINT NOT NULL REFERENCES public.balaustres(id) ON DELETE CASCADE,
  aberta_por UUID NULL REFERENCES public.obreiros(id),
  aberta_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  encerrada_em TIMESTAMPTZ NULL,
  status TEXT NOT NULL DEFAULT 'aberta',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_balaustre_votacoes_status
    CHECK (status IN ('aberta', 'encerrada'))
);

CREATE INDEX IF NOT EXISTS ix_balaustre_votacoes_balaustre
  ON public.balaustre_votacoes(balaustre_id, aberta_em DESC);

CREATE TABLE IF NOT EXISTS public.balaustre_votantes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  votacao_id BIGINT NOT NULL REFERENCES public.balaustre_votacoes(id) ON DELETE CASCADE,
  obreiro_id UUID NOT NULL REFERENCES public.obreiros(id) ON DELETE CASCADE,
  elegivel BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_balaustre_votantes UNIQUE (votacao_id, obreiro_id)
);

CREATE TABLE IF NOT EXISTS public.balaustre_votos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  votacao_id BIGINT NOT NULL REFERENCES public.balaustre_votacoes(id) ON DELETE CASCADE,
  obreiro_id UUID NOT NULL REFERENCES public.obreiros(id) ON DELETE CASCADE,
  voto TEXT NOT NULL,
  justificativa TEXT NULL,
  votado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_balaustre_votos_por_membro UNIQUE (votacao_id, obreiro_id),
  CONSTRAINT chk_balaustre_votos_voto
    CHECK (voto IN ('aprovar', 'pedir_correcao', 'rejeitar'))
);

