-- 009_primeiro_vigilante_trilha_aprendiz.sql
-- Fundação da trilha individual de estudos dos Aprendizes.

INSERT INTO public.cargos (codigo, nome_exibicao, ativo)
VALUES ('PRIMEIRO_VIGILANTE', '1º Vigilante', TRUE)
ON CONFLICT (codigo) DO UPDATE
SET
  nome_exibicao = EXCLUDED.nome_exibicao,
  ativo = EXCLUDED.ativo;

CREATE TABLE IF NOT EXISTS public.trilha_aprendiz (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aprendiz_id UUID NOT NULL REFERENCES public.obreiros(id) ON DELETE CASCADE,
  etapa_ordem SMALLINT NOT NULL,
  titulo_etapa TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'nao_iniciado',
  data_disponibilizacao TIMESTAMPTZ NULL,
  data_entrega TIMESTAMPTZ NULL,
  data_revisao TIMESTAMPTZ NULL,
  observacao_vigilante TEXT NULL,
  arquivo_entrega TEXT NULL,
  revisado_por UUID NULL REFERENCES public.obreiros(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_trilha_aprendiz_etapa UNIQUE (aprendiz_id, etapa_ordem),
  CONSTRAINT chk_trilha_aprendiz_etapa CHECK (etapa_ordem BETWEEN 1 AND 8),
  CONSTRAINT chk_trilha_aprendiz_status CHECK (
    status IN (
      'nao_iniciado',
      'disponibilizado',
      'aguardando_entrega',
      'recebido',
      'revisado',
      'concluido',
      'apto_para_certificado',
      'certificado_solicitado'
    )
  )
);

CREATE INDEX IF NOT EXISTS ix_trilha_aprendiz_aprendiz
  ON public.trilha_aprendiz(aprendiz_id, etapa_ordem);

CREATE INDEX IF NOT EXISTS ix_trilha_aprendiz_status
  ON public.trilha_aprendiz(status, etapa_ordem);
