-- 015_hospitaleiro_assistencia.sql
-- Cargo oficial de hospitalaria + estrutura inicial de ocorrencias assistenciais.

INSERT INTO public.cargos (codigo, nome_exibicao, ativo)
VALUES ('HOSPITALEIRO', 'Mestre Hospitaleiro', TRUE)
ON CONFLICT (codigo) DO UPDATE
SET
  nome_exibicao = EXCLUDED.nome_exibicao,
  ativo = EXCLUDED.ativo;

CREATE TABLE IF NOT EXISTS public.ocorrencias_assistenciais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_ocorrencia TEXT NOT NULL DEFAULT 'assistencia_geral',
  status TEXT NOT NULL DEFAULT 'aberta',
  prioridade TEXT NOT NULL DEFAULT 'media',
  obreiro_id UUID NULL REFERENCES public.obreiros(id),
  nome_familiar TEXT NULL,
  parentesco TEXT NULL,
  descricao TEXT NOT NULL,
  necessita_visita BOOLEAN NOT NULL DEFAULT FALSE,
  necessita_apoio_financeiro BOOLEAN NOT NULL DEFAULT FALSE,
  valor_solicitado NUMERIC(12,2) NULL,
  valor_aprovado NUMERIC(12,2) NULL,
  encaminhar_para TEXT NOT NULL DEFAULT 'nenhum',
  data_ocorrencia DATE NULL,
  data_proxima_acao DATE NULL,
  observacao_status TEXT NULL,
  origem_registro TEXT NOT NULL DEFAULT 'manual',
  created_by UUID NULL REFERENCES public.obreiros(id),
  updated_by UUID NULL REFERENCES public.obreiros(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_ocorrencia_tipo CHECK (tipo_ocorrencia IN ('saude', 'nascimento', 'falecimento', 'assistencia_geral', 'solidariedade')),
  CONSTRAINT chk_ocorrencia_status CHECK (status IN ('aberta', 'em_acompanhamento', 'concluida', 'cancelada')),
  CONSTRAINT chk_ocorrencia_prioridade CHECK (prioridade IN ('baixa', 'media', 'alta', 'urgente')),
  CONSTRAINT chk_ocorrencia_encaminhar CHECK (encaminhar_para IN ('nenhum', 'veneravel', 'tesoureiro', 'ambos'))
);

CREATE INDEX IF NOT EXISTS ix_ocorrencias_assistenciais_status
  ON public.ocorrencias_assistenciais(status);

CREATE INDEX IF NOT EXISTS ix_ocorrencias_assistenciais_data_ocorrencia
  ON public.ocorrencias_assistenciais(data_ocorrencia DESC);

CREATE INDEX IF NOT EXISTS ix_ocorrencias_assistenciais_obreiro
  ON public.ocorrencias_assistenciais(obreiro_id);
