-- 018_gestoes_nominata_secretaria.sql
-- Estrutura a nominata oficial por gestao com periodo flexivel.

CREATE TABLE IF NOT EXISTS public.gestoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  inicio_em DATE NOT NULL,
  encerrada_em DATE NULL,
  status TEXT NOT NULL DEFAULT 'aberta',
  observacao TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_gestoes_status
    CHECK (status IN ('aberta', 'encerrada')),
  CONSTRAINT chk_gestoes_periodo
    CHECK (encerrada_em IS NULL OR encerrada_em >= inicio_em)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_gestoes_abertas
  ON public.gestoes(status)
  WHERE status = 'aberta';

ALTER TABLE public.atribuicoes_cargo
  ADD COLUMN IF NOT EXISTS gestao_id BIGINT NULL REFERENCES public.gestoes(id);

CREATE INDEX IF NOT EXISTS ix_atribuicoes_cargo_gestao
  ON public.atribuicoes_cargo(gestao_id, cargo_id);

DO $$
DECLARE
    v_gestao_id BIGINT;
BEGIN
    SELECT id
      INTO v_gestao_id
      FROM public.gestoes
     WHERE status = 'aberta'
     ORDER BY inicio_em DESC, id DESC
     LIMIT 1;

    IF v_gestao_id IS NULL THEN
        INSERT INTO public.gestoes (titulo, inicio_em, status, observacao)
        VALUES ('Gestao atual', CURRENT_DATE, 'aberta', 'Gestao inicial criada pela migracao 018.')
        RETURNING id INTO v_gestao_id;
    END IF;

    UPDATE public.atribuicoes_cargo
       SET gestao_id = v_gestao_id
     WHERE gestao_id IS NULL;
END $$;

INSERT INTO public.cargos (codigo, nome_exibicao, ativo)
VALUES
  ('ORADOR', 'Orador', TRUE),
  ('GUARDA_DA_LEI', 'Guarda da Lei', TRUE),
  ('MESTRE_BANQUETES', 'Mestre de Banquetes', TRUE),
  ('TESOUREIRO', 'Tesoureiro', TRUE),
  ('SECRETARIO', 'Secretario', TRUE),
  ('VENERAVEL', 'Veneravel Mestre', TRUE),
  ('PRIMEIRO_VIGILANTE', '1º Vigilante', TRUE),
  ('SEGUNDO_VIGILANTE', '2º Vigilante', TRUE),
  ('ADMINISTRADOR', 'Administrador', TRUE),
  ('BIBLIOTECARIO', 'Bibliotecario', TRUE),
  ('CHANCELER', 'Chanceler', TRUE),
  ('HOSPITALEIRO', 'Hospitaleiro', TRUE),
  ('PRIMEIRO_DIACONO', '1º Diacono', TRUE),
  ('SEGUNDO_DIACONO', '2º Diacono', TRUE),
  ('MESTRE_DE_CERIMONIAS', 'Mestre de Cerimonias', TRUE),
  ('ARQUITETO', 'Arquiteto', TRUE),
  ('PORTA_ESTANDARTE', 'Porta-Estandarte', TRUE),
  ('PORTA_ESPADA', 'Porta-Espada', TRUE),
  ('GUARDA_DO_TEMPLO', 'Guarda do Templo', TRUE),
  ('PRIMEIRO_EXPERTO', '1º Experto', TRUE),
  ('SEGUNDO_EXPERTO', '2º Experto', TRUE),
  ('COBRIDOR', 'Cobridor', TRUE),
  ('MESTRE_DE_HARMONIA', 'Mestre de Harmonia', TRUE)
ON CONFLICT (codigo) DO UPDATE
SET
  nome_exibicao = EXCLUDED.nome_exibicao,
  ativo = EXCLUDED.ativo;

CREATE OR REPLACE FUNCTION public.atribuir_cargo(
  p_cargo_codigo TEXT,
  p_obreiro_id UUID,
  p_gestao_id BIGINT DEFAULT NULL,
  p_inicio_em TIMESTAMPTZ DEFAULT NOW(),
  p_observacao TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
  v_cargo_id BIGINT;
  v_gestao_id BIGINT;
BEGIN
  SELECT id
    INTO v_cargo_id
    FROM public.cargos
   WHERE codigo = p_cargo_codigo
     AND ativo = TRUE;

  IF v_cargo_id IS NULL THEN
    RAISE EXCEPTION 'Cargo "%" nao encontrado ou inativo', p_cargo_codigo;
  END IF;

  IF p_gestao_id IS NOT NULL THEN
    v_gestao_id := p_gestao_id;
  ELSE
    SELECT id
      INTO v_gestao_id
      FROM public.gestoes
     WHERE status = 'aberta'
     ORDER BY inicio_em DESC, id DESC
     LIMIT 1;
  END IF;

  IF v_gestao_id IS NULL THEN
    RAISE EXCEPTION 'Nenhuma gestao aberta encontrada para atribuir o cargo "%" ', p_cargo_codigo;
  END IF;

  IF EXISTS (
    SELECT 1
      FROM public.atribuicoes_cargo
     WHERE cargo_id = v_cargo_id
       AND fim_em IS NULL
       AND gestao_id = v_gestao_id
       AND obreiro_id = p_obreiro_id
  ) THEN
    UPDATE public.atribuicoes_cargo
       SET observacao = COALESCE(p_observacao, observacao)
     WHERE cargo_id = v_cargo_id
       AND fim_em IS NULL
       AND gestao_id = v_gestao_id
       AND obreiro_id = p_obreiro_id;
    RETURN;
  END IF;

  UPDATE public.atribuicoes_cargo
     SET fim_em = p_inicio_em
   WHERE cargo_id = v_cargo_id
     AND gestao_id = v_gestao_id
     AND fim_em IS NULL;

  INSERT INTO public.atribuicoes_cargo (cargo_id, obreiro_id, gestao_id, inicio_em, observacao)
  VALUES (v_cargo_id, p_obreiro_id, v_gestao_id, p_inicio_em, p_observacao);
END;
$$;
