-- 018_eventos_e_visitas_sessao.sql
-- Estrutura formal de eventos e visitas externas vinculados a sessoes.

CREATE TABLE IF NOT EXISTS public.eventos_sessao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sessao_id INTEGER NOT NULL REFERENCES public.sessoes(id) ON DELETE CASCADE,
  tipo_evento TEXT NOT NULL,
  titulo TEXT NOT NULL,
  descricao TEXT NULL,
  data_evento DATE NULL,
  local TEXT NULL,
  promotor TEXT NULL,
  loja_relacionada TEXT NULL,
  oriente TEXT NULL,
  observacao TEXT NULL,
  created_by UUID NULL REFERENCES public.obreiros(id),
  updated_by UUID NULL REFERENCES public.obreiros(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_eventos_sessao_tipo
    CHECK (
      tipo_evento IN (
        'evento_promovido',
        'evento_participado',
        'congresso',
        'palestra',
        'atividade_social',
        'atividade_civica',
        'sessao_branca'
      )
    )
);

CREATE INDEX IF NOT EXISTS ix_eventos_sessao_sessao
  ON public.eventos_sessao(sessao_id, tipo_evento, data_evento);

CREATE INDEX IF NOT EXISTS ix_eventos_sessao_tipo_data
  ON public.eventos_sessao(tipo_evento, data_evento);

CREATE TABLE IF NOT EXISTS public.visitas_externas_sessao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sessao_id INTEGER NOT NULL REFERENCES public.sessoes(id) ON DELETE CASCADE,
  obreiro_id UUID NULL REFERENCES public.obreiros(id) ON DELETE SET NULL,
  obreiro_nome_livre TEXT NULL,
  loja_visitada TEXT NULL,
  potencia_obediencia TEXT NULL,
  oriente TEXT NULL,
  data_visita DATE NULL,
  observacao TEXT NULL,
  origem_registro TEXT NOT NULL DEFAULT 'saco_propostas',
  created_by UUID NULL REFERENCES public.obreiros(id),
  updated_by UUID NULL REFERENCES public.obreiros(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_visitas_externas_sessao_sessao
  ON public.visitas_externas_sessao(sessao_id, data_visita);

CREATE INDEX IF NOT EXISTS ix_visitas_externas_sessao_loja
  ON public.visitas_externas_sessao(loja_visitada);
