-- 045_convites_externos_secretaria.sql
-- Base funcional para mural de convites externos gerenciado pela Secretaria.

CREATE TABLE IF NOT EXISTS public.convites_externos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loja_id INTEGER NOT NULL REFERENCES public.lojas(id),
  source TEXT NOT NULL DEFAULT 'external',
  external_source TEXT NULL,
  external_id TEXT NULL,
  integration_payload JSONB NULL,
  tipo TEXT NOT NULL DEFAULT 'outro',
  titulo TEXT NOT NULL,
  loja_origem TEXT NULL,
  potencia TEXT NULL,
  grau TEXT NULL,
  data_hora TIMESTAMPTZ NULL,
  cidade TEXT NULL,
  local TEXT NULL,
  prazo_confirmacao TIMESTAMPTZ NULL,
  contatos TEXT NULL,
  valor TEXT NULL,
  traje TEXT NULL,
  descricao TEXT NULL,
  texto_original TEXT NULL,
  status TEXT NOT NULL DEFAULT 'rascunho',
  fixado BOOLEAN NOT NULL DEFAULT FALSE,
  anexo_mime TEXT NULL,
  anexo_nome TEXT NULL,
  anexo_bytes TEXT NULL,
  anexo_expires_at TIMESTAMPTZ NULL,
  anexo_deleted_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_convites_externos_source CHECK (source IN ('internal', 'external', 'integration')),
  CONSTRAINT chk_convites_externos_status CHECK (status IN ('rascunho', 'publicado', 'cancelado', 'encerrado', 'expirado'))
);

CREATE INDEX IF NOT EXISTS ix_convites_externos_loja_status_data
  ON public.convites_externos (loja_id, status, data_hora);

CREATE INDEX IF NOT EXISTS ix_convites_externos_loja_fixado
  ON public.convites_externos (loja_id, fixado, data_hora);

CREATE TABLE IF NOT EXISTS public.presencas_convite_externo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loja_id INTEGER NOT NULL REFERENCES public.lojas(id),
  convite_externo_id BIGINT NOT NULL REFERENCES public.convites_externos(id) ON DELETE CASCADE,
  obreiro_id UUID NOT NULL REFERENCES public.obreiros(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pendente',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_presencas_convite_externo UNIQUE (convite_externo_id, obreiro_id),
  CONSTRAINT chk_presencas_convite_externo_status CHECK (status IN ('pendente', 'confirmado', 'cancelado'))
);

CREATE INDEX IF NOT EXISTS ix_presencas_convite_externo_loja_status
  ON public.presencas_convite_externo (loja_id, status, updated_at DESC);
