-- 048_vida_loja_modulo.sql
-- Objetivo: Criar a estrutura básica para a Fase 1 da Vida da Loja (Sinais de Ausência e Contatos)

-- Tabela de Sinais de Cuidado Preventivos
CREATE TABLE IF NOT EXISTS public.vida_loja_sinais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loja_id INTEGER NOT NULL REFERENCES public.lojas(id),
    obreiro_id UUID NOT NULL REFERENCES public.obreiros(id),
    tipo TEXT NOT NULL, -- 'ausencias_consecutivas'
    status TEXT NOT NULL DEFAULT 'aberto', -- 'aberto', 'em_observacao', 'resolvido', 'arquivado'
    nivel TEXT NOT NULL DEFAULT 'baixo', -- 'baixo', 'medio', 'alto'
    detalhes TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at TIMESTAMPTZ NULL,
    resolved_by UUID REFERENCES public.obreiros(id), -- Auditoria via UUID de Obreiro
    motivo_resolucao TEXT NULL,
    CONSTRAINT chk_vida_loja_sinal_status CHECK (status IN ('aberto', 'em_observacao', 'resolvido', 'arquivado')),
    CONSTRAINT chk_vida_loja_sinal_tipo CHECK (tipo IN ('ausencias_consecutivas')),
    CONSTRAINT chk_vida_loja_sinal_nivel CHECK (nivel IN ('baixo', 'medio', 'alto'))
);

-- Prevenção de Sinais Duplicados: impede mais de um sinal aberto/em observação do mesmo tipo por obreiro
CREATE UNIQUE INDEX IF NOT EXISTS ux_vida_loja_sinais_abertos 
ON public.vida_loja_sinais (loja_id, obreiro_id, tipo) 
WHERE status IN ('aberto', 'em_observacao');

CREATE INDEX IF NOT EXISTS ix_vida_loja_sinais_loja_status ON public.vida_loja_sinais(loja_id, status);
CREATE INDEX IF NOT EXISTS ix_vida_loja_sinais_obreiro ON public.vida_loja_sinais(obreiro_id);

-- Tabela de Acompanhamentos Fraternos (Visões da Hospitalaria) com suporte a Soft Delete
CREATE TABLE IF NOT EXISTS public.vida_loja_acompanhamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loja_id INTEGER NOT NULL REFERENCES public.lojas(id),
    sinal_id BIGINT NULL REFERENCES public.vida_loja_sinais(id) ON DELETE SET NULL,
    obreiro_id UUID NOT NULL REFERENCES public.obreiros(id),
    data_contato DATE NOT NULL,
    meio_contato TEXT NOT NULL, -- 'telefone', 'whatsapp', 'presencial', 'visita', 'outro'
    resultado TEXT NOT NULL, -- Sumário básico
    proximo_acompanhamento DATE NULL,
    nivel_sigilo TEXT NOT NULL DEFAULT 'reservado', -- 'administrativo', 'reservado', 'sigiloso'
    observacoes_sigilosas TEXT NULL, -- Informações sensíveis (saúde/família)
    responsavel_id UUID NOT NULL REFERENCES public.obreiros(id), -- UUID do obreiro que registrou
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ NULL, -- Soft Delete
    deleted_by UUID REFERENCES public.obreiros(id),
    motivo_exclusao TEXT NULL,
    CONSTRAINT chk_vida_loja_acompanhamento_sigilo CHECK (nivel_sigilo IN ('administrativo', 'reservado', 'sigiloso')),
    CONSTRAINT chk_vida_loja_acompanhamento_meio CHECK (meio_contato IN ('telefone', 'whatsapp', 'presencial', 'visita', 'outro'))
);

CREATE INDEX IF NOT EXISTS ix_vida_loja_acompanhamentos_loja ON public.vida_loja_acompanhamentos(loja_id);
CREATE INDEX IF NOT EXISTS ix_vida_loja_acompanhamentos_obreiro ON public.vida_loja_acompanhamentos(obreiro_id);
