-- Migration 049: Alterações para a Fase 2 (Presença de Ágape e Anfitriões)
ALTER TABLE public.presencas_sessao ADD COLUMN IF NOT EXISTS presente_agape BOOLEAN DEFAULT NULL;

CREATE TABLE IF NOT EXISTS public.vida_loja_agape_anfitrioes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loja_id INTEGER NOT NULL REFERENCES public.lojas(id),
    sessao_id INTEGER NOT NULL REFERENCES public.sessoes(id) ON DELETE CASCADE,
    anfitriao_obreiro_id UUID NOT NULL REFERENCES public.obreiros(id),
    acolhido_obreiro_id UUID NULL REFERENCES public.obreiros(id),
    visitante_nome TEXT NULL,
    foco TEXT NOT NULL DEFAULT 'integracao',
    observacao TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID NULL REFERENCES public.obreiros(id),
    updated_at TIMESTAMPTZ NULL,
    deleted_at TIMESTAMPTZ NULL,
    deleted_by UUID NULL REFERENCES public.obreiros(id),
    CONSTRAINT chk_vida_loja_anfitriao_proposito CHECK (
        acolhido_obreiro_id IS NOT NULL
        OR visitante_nome IS NOT NULL
        OR foco = 'geral'
    )
);

-- Atualiza a check constraint de tipos de sinal
ALTER TABLE public.vida_loja_sinais DROP CONSTRAINT IF EXISTS chk_vida_loja_sinal_tipo;
ALTER TABLE public.vida_loja_sinais ADD CONSTRAINT chk_vida_loja_sinal_tipo CHECK (tipo IN ('ausencias_consecutivas', 'baixa_integracao_agape'));
