<?php

namespace App\Models;

use App\Config\Database;
use App\Core\Tenant\ResolvesStoreTenant;
use PDO;
use PDOException;

class ConviteExterno
{
    use ResolvesStoreTenant;

    private PDO $db;

    public function __construct()
    {
        $this->db = Database::getConnection();
        $this->ensureTables();
    }

    private function ensureTables(): void
    {
        // Mantém o módulo resiliente em ambientes onde as migrations ainda não foram aplicadas.
        $this->db->exec("
            CREATE TABLE IF NOT EXISTS public.convites_externos (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              loja_id INTEGER NOT NULL REFERENCES public.lojas(id),
              source TEXT NOT NULL DEFAULT 'external',
              external_source TEXT NULL,
              external_id TEXT NULL,
              integration_payload JSONB NULL,
              tipo TEXT NOT NULL DEFAULT 'outro',
              titulo TEXT NOT NULL,
              loja_origem TEXT NULL,
              potencia TEXT NULL,
              grau TEXT NULL,
              data_hora TIMESTAMPTZ NULL,
              cidade TEXT NULL,
              local TEXT NULL,
              prazo_confirmacao TIMESTAMPTZ NULL,
              contatos TEXT NULL,
              valor TEXT NULL,
              traje TEXT NULL,
              descricao TEXT NULL,
              texto_original TEXT NULL,
              status TEXT NOT NULL DEFAULT 'rascunho',
              fixado BOOLEAN NOT NULL DEFAULT FALSE,
              anexo_mime TEXT NULL,
              anexo_nome TEXT NULL,
              anexo_bytes TEXT NULL,
              anexo_expires_at TIMESTAMPTZ NULL,
              anexo_deleted_at TIMESTAMPTZ NULL,
              created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
              updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
              CONSTRAINT chk_convites_externos_source CHECK (source IN ('internal', 'external', 'integration')),
              CONSTRAINT chk_convites_externos_status CHECK (status IN ('rascunho', 'publicado', 'cancelado', 'encerrado', 'expirado'))
            );

            CREATE INDEX IF NOT EXISTS ix_convites_externos_loja_status_data
              ON public.convites_externos (loja_id, status, data_hora);

            CREATE INDEX IF NOT EXISTS ix_convites_externos_loja_fixado
              ON public.convites_externos (loja_id, fixado, data_hora);

            CREATE TABLE IF NOT EXISTS public.presencas_convite_externo (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              loja_id INTEGER NOT NULL REFERENCES public.lojas(id),
              convite_externo_id BIGINT NOT NULL REFERENCES public.convites_externos(id) ON DELETE CASCADE,
              obreiro_id UUID NOT NULL REFERENCES public.obreiros(id) ON DELETE CASCADE,
              status TEXT NOT NULL DEFAULT 'pendente',
              updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
              created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
              CONSTRAINT uq_presencas_convite_externo UNIQUE (convite_externo_id, obreiro_id),
              CONSTRAINT chk_presencas_convite_externo_status CHECK (status IN ('pendente', 'confirmado', 'cancelado'))
            );

            CREATE INDEX IF NOT EXISTS ix_presencas_convite_externo_loja_status
              ON public.presencas_convite_externo (loja_id, status, updated_at DESC);
        ");
    }

    public function criar(array $data, array $arquivo = [], ?string $autorId = null): bool
    {
        try {
        $anexoBytes = null;
        $anexoMime = null;
        $anexoNome = null;
        if (!empty($arquivo['conteudo_base64'])) {
            $detectedMime = trim((string) ($arquivo['mime'] ?? ''));
            $allowedMimes = ['application/pdf', 'image/jpeg', 'image/png', 'image/webp'];
            $conteudo = base64_decode((string) $arquivo['conteudo_base64'], true);
            if (!in_array($detectedMime, $allowedMimes, true) || $conteudo === false || strlen($conteudo) > 5 * 1024 * 1024) {
                return false;
            }
            $anexoBytes = base64_encode($conteudo);
            $anexoMime = $detectedMime;
            $anexoNome = trim((string) ($arquivo['nome'] ?? '')) ?: null;
        } elseif (($arquivo['error'] ?? UPLOAD_ERR_NO_FILE) === UPLOAD_ERR_OK && is_uploaded_file((string) ($arquivo['tmp_name'] ?? ''))) {
            $tmpName = (string) ($arquivo['tmp_name'] ?? '');
            $fileSize = (int) ($arquivo['size'] ?? 0);
            $maxBytes = 5 * 1024 * 1024;
            if ($fileSize <= 0 || $fileSize > $maxBytes) {
                return false;
            }

            $finfo = finfo_open(FILEINFO_MIME_TYPE);
            $detectedMime = $finfo ? (string) finfo_file($finfo, $tmpName) : '';
            if ($finfo) {
                finfo_close($finfo);
            }
            $allowedMimes = ['application/pdf', 'image/jpeg', 'image/png', 'image/webp'];
            if (!in_array($detectedMime, $allowedMimes, true)) {
                return false;
            }

            $conteudo = file_get_contents($tmpName);
            if ($conteudo !== false) {
                $anexoBytes = base64_encode($conteudo);
                $anexoMime = $detectedMime;
                $anexoNome = trim((string) ($arquivo['name'] ?? '')) ?: null;
            }
        }

        $stmt = $this->db->prepare("
            INSERT INTO convites_externos (
                loja_id,
                source,
                external_source,
                external_id,
                integration_payload,
                tipo,
                titulo,
                loja_origem,
                potencia,
                grau,
                data_hora,
                cidade,
                local,
                prazo_confirmacao,
                contatos,
                valor,
                traje,
                descricao,
                texto_original,
                status,
                fixado,
                anexo_mime,
                anexo_nome,
                anexo_bytes,
                anexo_expires_at,
                updated_at
            ) VALUES (
                :loja_id,
                'external',
                :external_source,
                :external_id,
                CAST(:integration_payload AS jsonb),
                :tipo,
                :titulo,
                :loja_origem,
                :potencia,
                :grau,
                :data_hora,
                :cidade,
                :local,
                :prazo_confirmacao,
                :contatos,
                :valor,
                :traje,
                :descricao,
                :texto_original,
                :status,
                :fixado,
                :anexo_mime,
                :anexo_nome,
                :anexo_bytes,
                :anexo_expires_at,
                NOW()
            )
        ");

        $dataHora = trim((string) ($data['data_hora'] ?? ''));
        $prazo = trim((string) ($data['prazo_confirmacao'] ?? ''));
        $diasAnexo = max(1, (int) ($_ENV['APP_CONVITE_ANEXO_TTL_DIAS'] ?? 14));

        return $stmt->execute([
            'loja_id' => $this->obterLojaAtualId(),
            'external_source' => trim((string) ($data['external_source'] ?? 'manual')) ?: 'manual',
            'external_id' => trim((string) ($data['external_id'] ?? '')) ?: null,
            'integration_payload' => null,
            'tipo' => trim((string) ($data['tipo'] ?? 'outro')) ?: 'outro',
            'titulo' => trim((string) ($data['titulo'] ?? '')),
            'loja_origem' => trim((string) ($data['loja_origem'] ?? '')) ?: null,
            'potencia' => trim((string) ($data['potencia'] ?? '')) ?: null,
            'grau' => trim((string) ($data['grau'] ?? '')) ?: null,
            'data_hora' => $dataHora !== '' ? $dataHora : null,
            'cidade' => trim((string) ($data['cidade'] ?? '')) ?: null,
            'local' => trim((string) ($data['local'] ?? '')) ?: null,
            'prazo_confirmacao' => $prazo !== '' ? $prazo : null,
            'contatos' => trim((string) ($data['contatos'] ?? '')) ?: null,
            'valor' => trim((string) ($data['valor'] ?? '')) ?: null,
            'traje' => trim((string) ($data['traje'] ?? '')) ?: null,
            'descricao' => trim((string) ($data['descricao'] ?? '')) ?: null,
            'texto_original' => trim((string) ($data['texto_original'] ?? '')) ?: null,
            'status' => trim((string) ($data['status'] ?? 'rascunho')) ?: 'rascunho',
            'fixado' => !empty($data['fixado']) ? 'true' : 'false',
            'anexo_mime' => $anexoMime,
            'anexo_nome' => $anexoNome,
            'anexo_bytes' => $anexoBytes,
            'anexo_expires_at' => $anexoBytes !== null && $dataHora !== '' ? date('c', strtotime($dataHora . ' +' . $diasAnexo . ' days')) : null,
        ]);
        } catch (PDOException $e) {
            if (($e->getCode() ?? '') === '42P01') {
                return false;
            }
            throw $e;
        }
    }

    public function listarRecentes(int $limite = 50): array
    {
        try {
        $limite = max(1, min($limite, 200));
        $stmt = $this->db->prepare("
            SELECT
                id,
                tipo,
                titulo,
                loja_origem,
                potencia,
                grau,
                data_hora,
                cidade,
                local,
                prazo_confirmacao,
                contatos,
                valor,
                traje,
                descricao,
                texto_original,
                status,
                fixado,
                anexo_mime,
                anexo_nome,
                anexo_expires_at,
                anexo_deleted_at,
                created_at,
                updated_at
            FROM convites_externos
            WHERE loja_id = :loja_id
            ORDER BY fixado DESC, data_hora ASC NULLS LAST, created_at DESC
            LIMIT :limite
        ");
        $stmt->bindValue('loja_id', $this->obterLojaAtualId(), PDO::PARAM_INT);
        $stmt->bindValue('limite', $limite, PDO::PARAM_INT);
        $stmt->execute();
        $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
        if ($rows === []) {
            return [];
        }

        $ids = array_values(array_filter(array_map(static fn(array $r): int => (int) ($r['id'] ?? 0), $rows), static fn(int $v): bool => $v > 0));
        if ($ids === []) {
            return $rows;
        }

        $placeholders = implode(',', array_fill(0, count($ids), '?'));
        $sqlTotais = "
            SELECT convite_externo_id, COUNT(*) FILTER (WHERE status = 'confirmado') AS total_confirmados
            FROM presencas_convite_externo
            WHERE loja_id = ?
              AND convite_externo_id IN ($placeholders)
            GROUP BY convite_externo_id
        ";
        $stmtTotais = $this->db->prepare($sqlTotais);
        $params = array_merge([$this->obterLojaAtualId()], $ids);
        $stmtTotais->execute($params);
        $totais = [];
        foreach ($stmtTotais->fetchAll(PDO::FETCH_ASSOC) as $t) {
            $totais[(int) ($t['convite_externo_id'] ?? 0)] = (int) ($t['total_confirmados'] ?? 0);
        }

        foreach ($rows as &$row) {
            $row['total_confirmados'] = $totais[(int) ($row['id'] ?? 0)] ?? 0;
        }
        unset($row);

        return $rows;
        } catch (PDOException $e) {
            if (($e->getCode() ?? '') === '42P01') {
                return [];
            }
            throw $e;
        }
    }

    public function listarPorPeriodo(string $inicio, string $fim): array
    {
        $inicio = trim($inicio);
        $fim = trim($fim);
        if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $inicio) || !preg_match('/^\d{4}-\d{2}-\d{2}$/', $fim)) {
            return [];
        }

        try {
            $stmt = $this->db->prepare("
                SELECT
                    id,
                    tipo,
                    titulo,
                    potencia,
                    grau,
                    data_hora,
                    cidade,
                    local,
                    status,
                    fixado
                FROM convites_externos
                WHERE loja_id = :loja_id
                  AND data_hora IS NOT NULL
                  AND data_hora::date BETWEEN :inicio AND :fim
                ORDER BY data_hora ASC, fixado DESC
            ");
            $stmt->execute([
                'loja_id' => $this->obterLojaAtualId(),
                'inicio' => $inicio,
                'fim' => $fim,
            ]);
            return $stmt->fetchAll(PDO::FETCH_ASSOC) ?: [];
        } catch (PDOException $e) {
            if (($e->getCode() ?? '') === '42P01') {
                return [];
            }
            throw $e;
        }
    }

    public function definirPresenca(int $conviteId, string $obreiroId, string $status): bool
    {
        try {
        if (!in_array($status, ['pendente', 'confirmado', 'cancelado'], true)) {
            return false;
        }
        $stmt = $this->db->prepare("
            INSERT INTO presencas_convite_externo (loja_id, convite_externo_id, obreiro_id, status, updated_at)
            VALUES (:loja_id, :convite_id, :obreiro_id, :status, NOW())
            ON CONFLICT (convite_externo_id, obreiro_id)
            DO UPDATE SET status = EXCLUDED.status, updated_at = NOW()
        ");
        return $stmt->execute([
            'loja_id' => $this->obterLojaAtualId(),
            'convite_id' => $conviteId,
            'obreiro_id' => $obreiroId,
            'status' => $status,
        ]);
        } catch (PDOException $e) {
            if (($e->getCode() ?? '') === '42P01') {
                return false;
            }
            throw $e;
        }
    }

    public function listarConfirmados(int $conviteId): array
    {
        try {
        $stmt = $this->db->prepare("
            SELECT o.nome, o.cim
            FROM presencas_convite_externo p
            JOIN obreiros o ON o.id = p.obreiro_id
            WHERE p.loja_id = :loja_id
              AND p.convite_externo_id = :convite_id
              AND p.status = 'confirmado'
            ORDER BY o.nome ASC
        ");
        $stmt->execute([
            'loja_id' => $this->obterLojaAtualId(),
            'convite_id' => $conviteId,
        ]);
        return $stmt->fetchAll(PDO::FETCH_ASSOC);
        } catch (PDOException $e) {
            if (($e->getCode() ?? '') === '42P01') {
                return [];
            }
            throw $e;
        }
    }

    public function removerAnexo(int $id): bool
    {
        try {
        $stmt = $this->db->prepare("
            UPDATE convites_externos
               SET anexo_mime = NULL,
                   anexo_nome = NULL,
                   anexo_bytes = NULL,
                   anexo_deleted_at = NOW(),
                   updated_at = NOW()
             WHERE id = :id
               AND loja_id = :loja_id
        ");

        return $stmt->execute([
            'id' => $id,
            'loja_id' => $this->obterLojaAtualId(),
        ]);
        } catch (PDOException $e) {
            if (($e->getCode() ?? '') === '42P01') {
                return false;
            }
            throw $e;
        }
    }

    private function obterLojaAtualId(): int
    {
        return $this->resolveCurrentStoreId($this->db);
    }
}
